# # Calling function  
# result = chr(102) # It returns string representation of a char  
# result2 = chr(625996)  
# # Displaying result  
# print(result)  
# print(result2)  
# # Verify, is it string type?  
# print("is it string type:", type(result) is str)  
# print(0x110000)      
a = complex(1) # Passing sing   le parameter  
b = complex(1.5,2.9) # Passing both parameters  
# Displaying result  
print(a)  
print(b)

print(type(a) is complex)